
name: Sean Butler
markdown: kramdown


include:
  - assets

collections:
    posts:
        output: true
    projects:
        output: true
        permalink: /projects/:title/
    writings:
        output: true
        permalink: /writings/:title/
    talks:
        output: true
        permalink: /talks/:title/
