
name: Sean Butler
markdown: kramdown

exclude:
  - assets/slides

collections:
    posts:
        output: true
    projects:
        output: true
        permalink: /projects/:title/
    writings:
        output: true
        permalink: /writings/:title/
    talks:
        output: true
        permalink: /talks/:title/
